### ISSUE TITLE
推断 CUDA out of memory

### ISSUE THREAD

**Issue by z0y1** [PeterL1n/RobustVideoMatting#163]
根据推断文档，写了个简单的实时处理相机的demo，可以跑起来，但是正常显示几秒钟后稳定出现`CUDA out of memory`，加上了`torch.cuda.empty_cache()`，依旧没有效果。

错误信息如下:
```txt
Traceback (most recent call last):
  File "E:\Programs\Fractal\ThingsPlatform\playground\matting\camera_test02.py", line 39, in <module>
    fgr, pha, *rec = model(src, *rec, downsample_ratio=0.25)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\OpenSource/ai/matting/RobustVideoMatting\model\model.py", line 61, in forward
    fgr_residual, pha = self.refiner(src, src_sm, fgr_residual, pha, hid)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\OpenSource/ai/matting/RobustVideoMatting\model\deep_guided_filter.py", line 61, in forward
    return self.forward_single_frame(fine_src, base_src, base_fgr, base_pha, base_hid)
  File "F:\OpenSource/ai/matting/RobustVideoMatting\model\deep_guided_filter.py", line 39, in forward_single_frame
    b = F.interpolate(b, (H, W), mode='bilinear', align_corners=False)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 3709, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 8.00 GiB total capacity; 5.72 GiB already allocated; 18.91 MiB free; 5.83 GiB reserved in total by PyTorch)     
[ WARN:0@9.415] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
```

程序代码如下:
```python
import sys
import cv2
import numpy
import torch
from torchvision import transforms

# github clone目录
GIT_CLONE_PATH = "F:/OpenSource/ai/matting/RobustVideoMatting"

capture = cv2.VideoCapture(0)

capture.set(cv2.CAP_PROP_FRAME_WIDTH, 1920)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, 1080)

cam_width = capture.get(cv2.CAP_PROP_FRAME_WIDTH)
cam_height = capture.get(cv2.CAP_PROP_FRAME_HEIGHT)
print("相机分辨率: {}x{}".format(cam_width, cam_height))

sys.path.append(GIT_CLONE_PATH)

from model import MattingNetwork

model = MattingNetwork(variant="mobilenetv3").eval().cuda()
model.load_state_dict(
    torch.load("{}/Models/rvm_mobilenetv3.pth".format(GIT_CLONE_PATH))
)

rec = [None] * 4 # 初始记忆
bgr = torch.tensor([0.47, 1, 0.6]).view(3, 1, 1).cuda() # 绿色背景

loader = transforms.ToTensor()

while True:
    ret, frame = capture.read()

    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    src = loader(numpy.asarray(frame)).to("cuda", torch.float32).unsqueeze(0)

    fgr, pha, *rec = model(src, *rec, downsample_ratio=0.25)

    com = fgr * pha + bgr * (1 - pha)
    com = com.mul(255).byte().cpu().permute(0, 2, 3, 1).numpy()[0]
    com = cv2.cvtColor(com, cv2.COLOR_RGB2BGR)

    cv2.imshow("frame", com)
    
    # not working
    torch.cuda.empty_cache()

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

capture.release()
cv2.destroyAllWindows()
```

**Comment by PeterL1n** [comment]
推理的时候用 with torch.no_grad(): 这样省很多显存。

**Comment by z0y1** [comment]
多谢~~，用了with torch.no_grad():，现在稳定运行，没有`CUDA out of memory`了
