### ISSUE TITLE
is it possible to add .gif or .mp4 video insted of image/green/white background image?

### ISSUE THREAD

**Issue by akashAD98** [PeterL1n/RobustVideoMatting#207]
I want to add .gif  or .mp4 video in my background,instead of static image
@PeterL1n @

**Comment by akashAD98** [comment]
https://github.com/PeterL1n/RobustVideoMatting/issues/199

**Comment by Asthestarsfalll** [comment]
You need to chage the [bgr](https://github.com/PeterL1n/RobustVideoMatting/blob/master/inference.py#L135) from constant to corresponding frame in gif or video.
```python
    if (output_composition is not None) and (output_type == 'video'):
        bgr_source = VideoReader(bgr_dir, transform)
        bgr_reader = DataLoader(source, batch_size=bgr_source, pin_memory=True, num_workers=num_workers)
    try:
        with torch.no_grad():
            bar = tqdm(total=len(source), disable=not progress, dynamic_ncols=True)
            rec = [None] * 4
            for src, bgr in zip(reader, bgr_reader):

                if downsample_ratio is None:
                    downsample_ratio = auto_downsample_ratio(*src.shape[2:])

                src = src.to(device, dtype, non_blocking=True).unsqueeze(0) # [B, T, C, H, W]
                fgr, pha, *rec = model(src, *rec, downsample_ratio)

                if output_foreground is not None:
                    writer_fgr.write(fgr[0])
                if output_alpha is not None:
                    writer_pha.write(pha[0])
                if output_composition is not None:
                    if output_type == 'video':
                        com = fgr * pha + bgr * (1 - pha)
                    else:
                        fgr = fgr * pha.gt(0)
                        com = torch.cat([fgr, pha], dim=-3)
                    writer_com.write(com[0])
                
                bar.update(src.size(1))
```

**Comment by akashAD98** [comment]
@Asthestarsfalll  im not able to get output according to this, I added this code into inference.py
& passed video as input for background in bgr_dir & getting same green background instead of my custom video.

```
    if (output_composition is not None) and (output_type == 'video'):
        bgr_dir="/content/istock10minvide.mp4"
        bgr_source = VideoReader(bgr_dir, transform)
        bgr_reader = DataLoader(source, batch_size=bgr_source, pin_memory=True, num_workers=num_workers)

```

I used this command
```
from inference import convert_video

convert_video(
    model,                           # The model, can be on any device (cpu or cuda).
    input_source='/content/opvid_10_22.mp4',        # A video file or an image sequence directory.
    output_type='video',             # Choose "video" or "png_sequence"
    output_composition='/content/drive/MyDrive/Takeout/com.mp4',    # File path if video; directory path if png sequence.
    #output_alpha="pha.mp4",          # [Optional] Output the raw alpha prediction.
    #output_foreground="fgr.mp4",     # [Optional] Output the raw foreground prediction.
    output_video_mbps=4,             # Output video mbps. Not needed for png sequence.
    downsample_ratio=None,           # A hyperparameter to adjust or use None for auto.
    seq_chunk=12,                    # Process n frames at once for better parallelism.
)

```

**Comment by akashAD98** [comment]
https://github.com/PeterL1n/BackgroundMattingV2/issues/191
@Asthestarsfalll can you please help me ?

**Comment by Asthestarsfalll** [comment]
@akashAD98 
Can you upload the codes?
It seems that you did not use your own video, cause the way of composing video is unchanged.
Make sure you modify like this:
![image](https://user-images.githubusercontent.com/72954905/206663168-dddfc4f1-0b08-48aa-8fb6-7cfa218659ec.png)

**Comment by akashAD98** [comment]
@Asthestarsfalll I have assigned path of my video ,still not working
line 116 I have given the path of the video  **bgr_dir** ="op_bg.mp4"

<img width="510" alt="image" src="https://user-images.githubusercontent.com/62583018/207023134-8d085f0c-dcd9-47db-9390-7f820286e509.png">




[inference_rvm_video.text.zip](https://github.com/PeterL1n/RobustVideoMatting/files/10207017/inference_rvm_video.text.zip)

**Comment by Asthestarsfalll** [comment]
@akashAD98 
oh, just modify like this
bgr_reader = DataLoader(bgr_source, batch_size=seq_chunk, pin_memory=True, num_workers=num_workers)

**Comment by akashAD98** [comment]
@Asthestarsfalll i did changes still getting same op with green bg
<img width="406" alt="image" src="https://user-images.githubusercontent.com/62583018/207038522-c641d956-0933-4347-ba62-e41235c6ca4f.png">

**Comment by Asthestarsfalll** [comment]
@akashAD98 
My code:
```python
    if (output_composition is not None) and (output_type == 'video'):
        # bgr = torch.tensor([120, 255, 155], device=device, dtype=dtype).div(255).view(1, 1, 3, 1, 1)
        bgr_source = VideoReader("./asianboss.mp4", transform)
        bgr_reader = DataLoader(bgr_source, batch_size=seq_chunk, pin_memory=True, num_workers=num_workers)
    try:
        with torch.no_grad():
            bar = tqdm(total=len(source), disable=not progress, dynamic_ncols=True)
            rec = [None] * 4
            for (src, bgr) in zip(reader, bgr_reader):

                if downsample_ratio is None:
                    downsample_ratio = auto_downsample_ratio(*src.shape[2:])

                src = src.to(device, dtype, non_blocking=True).unsqueeze(0) # [B, T, C, H, W]
                fgr, pha, *rec = model(src, *rec, downsample_ratio)

                if output_foreground is not None:
                    writer_fgr.write(fgr[0])
                if output_alpha is not None:
                    writer_pha.write(pha[0])
                if output_composition is not None:
                    if output_type == 'video':
                        com = fgr * pha + bgr * (1 - pha)
                    else:
                        fgr = fgr * pha.gt(0)
                        com = torch.cat([fgr, pha], dim=-3)
                    writer_com.write(com[0])
                bar.update(src.size(1))
```

result:
![image](https://user-images.githubusercontent.com/72954905/207044732-dc753b10-9459-45c7-a0b0-6d4680ffd466.png)

**Comment by akashAD98** [comment]
@Asthestarsfalll  are you using this repo https://github.com/PeterL1n/RobustVideoMatting ??
& this command? i did all changes inside the inference.py ,I'm correct ?
```
from inference import convert_video

convert_video(
    model,                           # The model, can be on any device (cpu or cuda).
    input_source='input.mp4',        # A video file or an image sequence directory.
    output_type='video',             # Choose "video" or "png_sequence"
    output_composition='com.mp4',    # File path if video; directory path if png sequence.
    output_alpha="pha.mp4",          # [Optional] Output the raw alpha prediction.
    output_foreground="fgr.mp4",     # [Optional] Output the raw foreground prediction.
    output_video_mbps=4,             # Output video mbps. Not needed for png sequence.
    downsample_ratio=None,           # A hyperparameter to adjust or use None for auto.
    seq_chunk=12,                    # Process n frames at once for better parallelism.
)
```

**Comment by akashAD98** [comment]
very strenge @Asthestarsfalll 
i tried it with your code ..still had the same issue. this is my google collab, please can you check  
[RVM_withcustom_video_bg.zip](https://github.com/PeterL1n/RobustVideoMatting/files/10209713/RVM_withcustom_video_bg.zip)

**Comment by akashAD98** [comment]
i solve issue. the command i need to run is this 

```
!python inference.py \
    --variant resnet50 \
    --checkpoint "/content/RobustVideoMatting/CHECKPOINT/rvm_resnet50.pth" \
    --device cuda \
    --input-source "/content/vidforbg.mp4" \
    --output-type video \
    --output-composition "composition_opop_ISTOCK.mp4" \
    #--output-alpha "alpha.mp4" \
    #--output-foreground "foreground.mp4" \
    --output-video-mbps 4 \
    --seq-chunk 12
```

also make sure if you're running it on google collab. you will get 1 error
```
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

then just  add cuda to bgr

```bgr=bgr.to(device)```

@Asthestarsfalll thanks for your help mate

**Comment by akashAD98** [comment]
it has one issue we need to resize both videos & also there duration

**Comment by Asthestarsfalll** [comment]
@akashAD98
1. Use the same transform:
```python
        bgr_source = VideoReader("xxx.mp4", transform)  # there, the variable 'transform' is defined before
```
2. Use [`SequentialSampler`](https://pytorch.org/docs/stable/data.html#torch.utils.data.SequentialSampler) may be helpful. Or just use a counter to control when to end the inference loop

**Comment by akashAD98** [comment]
@Asthestarsfalll yes but im already using transform here    https://github.com/PeterL1n/RobustVideoMatting/blob/81a10937c73f68eeddb863221c61fe6a60a1cca2/inference_utils.py#L55,   I&  [SequentialSampler](https://pytorch.org/docs/stable/data.html#torch.utils.data.SequentialSampler) are same right?

**Comment by akashAD98** [comment]
@Asthestarsfalll 
```
duration_bgr = len(bgr_reader)
print("duration/length of backgrVID",duration_bgr)
```

```
with torch.no_grad():
            bar = tqdm(total=len(source), disable=not progress, dynamic_ncols=True)

            ##ImageSequenceReader

            counter=0
            rec = [None] * 4
            for (src, bgr) in zip(reader, bgr_reader):

                if downsample_ratio is None:
                    downsample_ratio = auto_downsample_ratio(*src.shape[2:])
                counter+=1
                print(counter)
                ### datset
                if counter >= duration_bgr:
                     break
```

im getting this error

```
#######
duration/length of backgrVID 1753
size
  0% 0/353 [00:00<?, ?it/s]1
Traceback (most recent call last):
  File "inference.py", line 228, in <module>
    converter.convert(
  File "inference.py", line 204, in convert
    convert_video(self.model, device=self.device, dtype=torch.float32, *args, **kwargs)
  File "inference.py", line 170, in convert_video
    com = fgr * pha + bgr * (1 - pha)
RuntimeError: The size of tensor a (720) must match the size of tensor b (1920) at non-singleton dimension 4
  0% 0/353 [00:01<?, ?it/s]

```

**Comment by Asthestarsfalll** [comment]
@akashAD98 
It seem that you did not specify the augment `input-resize`. So the transform will be `ToTensor` without resize by default.
Add resize to transform by your own or specify `input-resize`
```python
    if input_resize is not None:
        transform = transforms.Compose([
            transforms.Resize(input_resize[::-1]),
            transforms.ToTensor()
        ])
    else:
        transform = transforms.ToTensor()
```

**Comment by akashAD98** [comment]
@Asthestarsfalll solve problem thanks mate

**Comment by darwinOne** [comment]
@akashAD98 Sir, can I see your code running successfully on colab?

**Comment by akashAD98** [comment]
@darwinOne yes it’s working fine

**Comment by darwinOne** [comment]
@akashAD98 can you share the code file, please?

**Comment by akashAD98** [comment]
@darwinOne yes please drop your mail

**Comment by FONCHIEH** [comment]
> @darwinOne yes please drop your mail是的，请投递您的邮件

fonchieh@gmail.com
thanks
