### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'CHECKPOINT'

### ISSUE THREAD

**Issue by hua74138** [PeterL1n/RobustVideoMatting#274]
运行inference.py时报错：
FileNotFoundError: [Errno 2] No such file or directory: 'CHECKPOINT'

**Comment by Liam203** [comment]
你要先创建这个文件夹，然后把文件夹地址放到命令行

**Comment by LiWeisuper** [comment]
请问你解决了么？
我添加空文件后出现权限错误
![Uploading 无标题.png…]()

**Comment by LiWeisuper** [comment]
请问你解决了么？
我创建文件夹后出现权限错误

Traceback (most recent call last):
  File "E:\python\myapps\AI\RobustVideoMatting-1.0.0\inference.py", line 193, in <module>
    converter = Converter(args.variant, args.checkpoint, args.device)
  File "E:\python\myapps\AI\RobustVideoMatting-1.0.0\inference.py", line 164, in __init__
    self.model.load_state_dict(torch.load(checkpoint, map_location=device))
  File "C:\ProgramData\anaconda3\envs\rvm\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\ProgramData\anaconda3\envs\rvm\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\ProgramData\anaconda3\envs\rvm\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'CHECKPOINT'
